apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapi
  template:
    metadata:
      labels:
        app: bookapi
    spec:
      containers:
        - name: bookapi
          image: imvictr/bookcatalog:1.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: bookapi-ci-srv
spec:
  type: ClusterIP
  selector:
    app: bookapi
  ports:
  - name: bookapi
    protocol: TCP
    port: 80
    targetPort: 80