apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-catalogclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql
type: Opaque
data:
  MSSQL_SA_PASSWORD: cVZ3ZmNpSzhA